// AUTO-GENERATED by scripts/import-room-wifi-qr.ts — do not edit by hand.
// Per-room Wi-Fi credentials for Guest Chat A4 notice print.

export type RoomWifiCredential = {
  roomNo: string;
  ssid24: string;
  ssid5g: string;
  password: string;
  qr24Path: string;
  qr5gPath: string;
};

export const ROOM_WIFI_BY_ROOM: Record<string, RoomWifiCredential> = {
  '201': { roomNo: '201', ssid24: "U+NetEC60", ssid5g: "U+NetEC60_5G", password: "A52D33A1#K", qr24Path: '/wifi-qr/201/24g.jpg', qr5gPath: '/wifi-qr/201/5g.jpg' },
  '202': { roomNo: '202', ssid24: "U+NetEC64", ssid5g: "U+NetEC64_5G", password: "#0F3GD51C2", qr24Path: '/wifi-qr/202/24g.jpg', qr5gPath: '/wifi-qr/202/5g.jpg' },
  '203': { roomNo: '203', ssid24: "U+NetEC68", ssid5g: "U+NetEC68_5G", password: "@ABA2AHA03", qr24Path: '/wifi-qr/203/24g.jpg', qr5gPath: '/wifi-qr/203/5g.jpg' },
  '205': { roomNo: '205', ssid24: "U+NetEC6C", ssid5g: "U+NetEC6C_5G", password: "53B698#1JF", qr24Path: '/wifi-qr/205/24g.jpg', qr5gPath: '/wifi-qr/205/5g.jpg' },
  '206': { roomNo: '206', ssid24: "U+NetEC70", ssid5g: "U+NetEC70_5G", password: "P5FC68234#", qr24Path: '/wifi-qr/206/24g.jpg', qr5gPath: '/wifi-qr/206/5g.jpg' },
  '207': { roomNo: '207', ssid24: "U+NetEC74", ssid5g: "U+NetEC74_5G", password: "0CDK6E#9E4", qr24Path: '/wifi-qr/207/24g.jpg', qr5gPath: '/wifi-qr/207/5g.jpg' },
  '208': { roomNo: '208', ssid24: "U+NetEC78", ssid5g: "U+NetEC78_5G", password: "0#H802593C", qr24Path: '/wifi-qr/208/24g.jpg', qr5gPath: '/wifi-qr/208/5g.jpg' },
  '209': { roomNo: '209', ssid24: "U+NetEC7C", ssid5g: "U+NetEC7C_5G", password: "41CE8G00#3", qr24Path: '/wifi-qr/209/24g.jpg', qr5gPath: '/wifi-qr/209/5g.jpg' },
  '301': { roomNo: '301', ssid24: "U+NetEC80", ssid5g: "U+NetEC80_5G", password: "7D8487@0HA", qr24Path: '/wifi-qr/301/24g.jpg', qr5gPath: '/wifi-qr/301/5g.jpg' },
  '302': { roomNo: '302', ssid24: "U+NetEC84", ssid5g: "U+NetEC84_5G", password: "01CEF99@0P", qr24Path: '/wifi-qr/302/24g.jpg', qr5gPath: '/wifi-qr/302/5g.jpg' },
  '303': { roomNo: '303', ssid24: "U+NetC930", ssid5g: "U+NetC930_5G", password: "6920F#G483", qr24Path: '/wifi-qr/303/24g.jpg', qr5gPath: '/wifi-qr/303/5g.jpg' },
  '305': { roomNo: '305', ssid24: "U+NetC934", ssid5g: "U+NetC934_5G", password: "FE#C51AG71", qr24Path: '/wifi-qr/305/24g.jpg', qr5gPath: '/wifi-qr/305/5g.jpg' },
  '306': { roomNo: '306', ssid24: "U+NetC938", ssid5g: "U+NetC938_5G", password: "698478#P0C", qr24Path: '/wifi-qr/306/24g.jpg', qr5gPath: '/wifi-qr/306/5g.jpg' },
  '307': { roomNo: '307', ssid24: "U+NetC93C", ssid5g: "U+NetC93C_5G", password: "0HCDD@2612", qr24Path: '/wifi-qr/307/24g.jpg', qr5gPath: '/wifi-qr/307/5g.jpg' },
  '308': { roomNo: '308', ssid24: "U+NetC940", ssid5g: "U+NetC940_5G", password: "601AD#988H", qr24Path: '/wifi-qr/308/24g.jpg', qr5gPath: '/wifi-qr/308/5g.jpg' },
  '309': { roomNo: '309', ssid24: "U+NetC944", ssid5g: "U+NetC944_5G", password: "@5E3DF166K", qr24Path: '/wifi-qr/309/24g.jpg', qr5gPath: '/wifi-qr/309/5g.jpg' },
  '501': { roomNo: '501', ssid24: "U+NetC948", ssid5g: "U+NetC948_5G", password: "94568G10#B", qr24Path: '/wifi-qr/501/24g.jpg', qr5gPath: '/wifi-qr/501/5g.jpg' },
  '502': { roomNo: '502', ssid24: "U+NetC94C", ssid5g: "U+NetC94C_5G", password: "H9AB3E62C@", qr24Path: '/wifi-qr/502/24g.jpg', qr5gPath: '/wifi-qr/502/5g.jpg' },
  '503': { roomNo: '503', ssid24: "U+NetC950", ssid5g: "U+NetC950_5G", password: "E808#37F2G", qr24Path: '/wifi-qr/503/24g.jpg', qr5gPath: '/wifi-qr/503/5g.jpg' },
  '505': { roomNo: '505', ssid24: "U+NetC954", ssid5g: "U+NetC954_5G", password: "1GDB4#1991", qr24Path: '/wifi-qr/505/24g.jpg', qr5gPath: '/wifi-qr/505/5g.jpg' },
  '506': { roomNo: '506', ssid24: "U+NetCA98", ssid5g: "U+NetCA98_5G", password: "16ACD11H@9", qr24Path: '/wifi-qr/506/24g.jpg', qr5gPath: '/wifi-qr/506/5g.jpg' },
  '507': { roomNo: '507', ssid24: "U+NetCA9C", ssid5g: "U+NetCA9C_5G", password: "BGD449#805", qr24Path: '/wifi-qr/507/24g.jpg', qr5gPath: '/wifi-qr/507/5g.jpg' },
  '508': { roomNo: '508', ssid24: "U+NetCAA0", ssid5g: "U+NetCAA0_5G", password: "63B45H#613", qr24Path: '/wifi-qr/508/24g.jpg', qr5gPath: '/wifi-qr/508/5g.jpg' },
  '601': { roomNo: '601', ssid24: "U+NetCB30", ssid5g: "U+NetCB30_5G", password: "8C370EK5#8", qr24Path: '/wifi-qr/601/24g.jpg', qr5gPath: '/wifi-qr/601/5g.jpg' },
  '602': { roomNo: '602', ssid24: "U+NetCAA8", ssid5g: "U+NetCAA8_5G", password: "12215P089#", qr24Path: '/wifi-qr/602/24g.jpg', qr5gPath: '/wifi-qr/602/5g.jpg' },
  '603': { roomNo: '603', ssid24: "U+NetCAAC", ssid5g: "U+NetCAAC_5G", password: "57223P4#CF", qr24Path: '/wifi-qr/603/24g.jpg', qr5gPath: '/wifi-qr/603/5g.jpg' },
  '605': { roomNo: '605', ssid24: "U+NetCAB0", ssid5g: "U+NetCAB0_5G", password: "F50FB7#3EK", qr24Path: '/wifi-qr/605/24g.jpg', qr5gPath: '/wifi-qr/605/5g.jpg' },
  '606': { roomNo: '606', ssid24: "U+NetCAB4", ssid5g: "U+NetCAB4_5G", password: "A@EA38H4BB", qr24Path: '/wifi-qr/606/24g.jpg', qr5gPath: '/wifi-qr/606/5g.jpg' },
  '607': { roomNo: '607', ssid24: "U+NetCAB8", ssid5g: "U+NetCAB8_5G", password: "480A5809K#", qr24Path: '/wifi-qr/607/24g.jpg', qr5gPath: '/wifi-qr/607/5g.jpg' },
  '608': { roomNo: '608', ssid24: "U+NetCABC", ssid5g: "U+NetCABC_5G", password: "364G3@0159", qr24Path: '/wifi-qr/608/24g.jpg', qr5gPath: '/wifi-qr/608/5g.jpg' },
  '701': { roomNo: '701', ssid24: "U+NetC980", ssid5g: "U+NetC980_5G", password: "4@H6AE8DD5", qr24Path: '/wifi-qr/701/24g.jpg', qr5gPath: '/wifi-qr/701/5g.jpg' },
  '702': { roomNo: '702', ssid24: "U+NetC984", ssid5g: "U+NetC984_5G", password: "DFP8B48C0#", qr24Path: '/wifi-qr/702/24g.jpg', qr5gPath: '/wifi-qr/702/5g.jpg' },
  '703': { roomNo: '703', ssid24: "U+NetC988", ssid5g: "U+NetC988_5G", password: "4P#D33EC69", qr24Path: '/wifi-qr/703/24g.jpg', qr5gPath: '/wifi-qr/703/5g.jpg' },
  '705': { roomNo: '705', ssid24: "U+NetC98C", ssid5g: "U+NetC98C_5G", password: "7EEGD10@56", qr24Path: '/wifi-qr/705/24g.jpg', qr5gPath: '/wifi-qr/705/5g.jpg' },
  '706': { roomNo: '706', ssid24: "U+NetC990", ssid5g: "U+NetC990_5G", password: "F00@50P696", qr24Path: '/wifi-qr/706/24g.jpg', qr5gPath: '/wifi-qr/706/5g.jpg' },
  '707': { roomNo: '707', ssid24: "U+NetC9A4", ssid5g: "U+NetC9A4_5G", password: "@4EE37D3H6", qr24Path: '/wifi-qr/707/24g.jpg', qr5gPath: '/wifi-qr/707/5g.jpg' },
  '708': { roomNo: '708', ssid24: "U+NetC998", ssid5g: "U+NetC998_5G", password: "585250#P19", qr24Path: '/wifi-qr/708/24g.jpg', qr5gPath: '/wifi-qr/708/5g.jpg' },
  '801': { roomNo: '801', ssid24: "U+NetC99C", ssid5g: "U+NetC99C_5G", password: "81GC0#7489", qr24Path: '/wifi-qr/801/24g.jpg', qr5gPath: '/wifi-qr/801/5g.jpg' },
  '802': { roomNo: '802', ssid24: "U+NetC9A0", ssid5g: "U+NetC9A0_5G", password: "9B9AEB4#KB", qr24Path: '/wifi-qr/802/24g.jpg', qr5gPath: '/wifi-qr/802/5g.jpg' },
};

export function roomWifiFor(roomNo: string | number | null | undefined): RoomWifiCredential | null {
  const key = String(roomNo ?? '').replace(/[^\d]/g, '');
  if (!key) return null;
  return ROOM_WIFI_BY_ROOM[key] ?? null;
}
